DELETE FROM `trinity_string` WHERE `entry` BETWEEN 13401 AND 13443;
INSERT INTO `trinity_string` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`) VALUES 
(13401, 'Alchemy', NULL, NULL, NULL, NULL, NULL, 'Alquimia', 'Alquimia', NULL),
(13402, 'Skinning', NULL, NULL, NULL, NULL, NULL, 'Desuello', 'Desuello', NULL),
(13403, 'Enchanting', NULL, NULL, NULL, NULL, NULL, 'Encantamiento', 'Encantamiento', NULL),
(13404, 'Herbalism', NULL, NULL, NULL, NULL, NULL, 'Herbolisteria', 'Herbolisteria', NULL),
(13405, 'Engineering', NULL, NULL, NULL, NULL, NULL, 'Ingeniería', 'Ingeniería', NULL),
(13406, 'Inscription', NULL, NULL, NULL, NULL, NULL, 'Inscripción', 'Inscripción', NULL),
(13407, 'Jewelcrafting', NULL, NULL, NULL, NULL, NULL, 'Joyería', 'Joyería', NULL),
(13408, 'Mining', NULL, NULL, NULL, NULL, NULL, 'Minería', 'Minería', NULL),
(13409, 'Leatherworking', NULL, NULL, NULL, NULL, NULL, 'Peletería', 'Peletería', NULL),
(13410, 'Tailoring', NULL, NULL, NULL, NULL, NULL, 'Sastrería', 'Sastrería', NULL),
(13411, 'Blacksmithing', NULL, NULL, NULL, NULL, NULL, 'Herrería', 'Herrería', NULL),
(13412, 'Give me my promotion PvP', NULL, NULL, NULL, NULL, NULL, 'Dame mi promoción PvP', 'Dame mi promoción PvP', NULL),
(13413, 'Give me my promotion PvE', NULL, NULL, NULL, NULL, NULL, 'Dame mi promoción PvE', 'Dame mi promoción PvE', NULL),
(13414, 'Warrior Arms PvP', NULL, NULL, NULL, NULL, NULL, 'Guerrero Armas PvP', 'Guerrero Armas PvP', NULL),
(13415, 'Warrior Fury PvP', NULL, NULL, NULL, NULL, NULL, 'Guerrero Furia PvP', 'Guerrero Furia PvP', NULL),
(13416, 'Warrior Protect PvP', NULL, NULL, NULL, NULL, NULL, 'Guerrero Protección PvP', 'Guerrero Protección PvP', NULL),
(13417, 'Warrior Arms PvE', NULL, NULL, NULL, NULL, NULL, 'Guerrero Armas PvE', 'Guerrero Armas PvE', NULL),
(13418, 'Warrior Fury PvE', NULL, NULL, NULL, NULL, NULL, 'Guerrero Furia PvE', 'Guerrero Furia PvE', NULL),
(13419, 'Warrior Protect PvE', NULL, NULL, NULL, NULL, NULL, 'Guerrero Protección PvE', 'Guerrero Protección PvP', NULL),
(13420, 'Paladin Retri PvP', NULL, NULL, NULL, NULL, NULL, 'Paladin Retri PvP', 'Paladin Retri PvP', NULL),
(13421, 'Paladin Protect PvP', NULL, NULL, NULL, NULL, NULL, 'Paladin Protect PvP', 'Paladin Protect PvP', NULL),
(13422, 'Paladin Holy PvP', NULL, NULL, NULL, NULL, NULL, 'Paladin Holy PvP', 'Paladin Holy PvP', NULL),
(13423, 'Paladin Retri PvE', NULL, NULL, NULL, NULL, NULL, 'Paladin Retri PvE', 'Paladin Retri PvE', NULL),
(13424, 'Paladin Protect PvE', NULL, NULL, NULL, NULL, NULL, 'Paladin Protect PvE', 'Paladin Protect PvE', NULL),
(13425, 'Paladin Holy PvE', NULL, NULL, NULL, NULL, NULL, 'Paladin Holy PvE', 'Paladin Holy PvE', NULL),
(13426, 'Priest Heal PvP', NULL, NULL, NULL, NULL, NULL, 'Priest Heal PvP', 'Priest Heal PvP', NULL),
(13427, 'Priest Shadow PvP', NULL, NULL, NULL, NULL, NULL, 'Priest Sombras PvP', 'Priest Sombras PvP', NULL),
(13428, 'Priest Heal PvE', NULL, NULL, NULL, NULL, NULL, 'Priest Heal PvE', 'Priest Heal PvE', NULL),
(13429, 'Priest Shadow PvE', NULL, NULL, NULL, NULL, NULL, 'Priest Sombras PvE', 'Priest Sombras PvE', NULL),
(13430, 'Shaman Heal PvP', NULL, NULL, NULL, NULL, NULL, 'Chamán Heal PvP', 'Chamán Heal PvP', NULL),
(13431, 'Shaman Elemental PvP', NULL, NULL, NULL, NULL, NULL, 'Chamán Elemental PvP', 'Chamán Elemental PvP', NULL),
(13432, 'Shaman Enhancement PvP', NULL, NULL, NULL, NULL, NULL, 'Chamán Mejora PvP', 'Chamán Mejora PvP', NULL),
(13433, 'Shaman Heal PvE', NULL, NULL, NULL, NULL, NULL, 'Chamán Heal PvE', 'Chamán Heal PvE', NULL),
(13434, 'Shaman Elemental PvE', NULL, NULL, NULL, NULL, NULL, 'Chamán Elemental PvE', 'Chamán Elemental PvE', NULL),
(13435, 'Shaman Enhancement PvE', NULL, NULL, NULL, NULL, NULL, 'Chamán Mejora PvE', 'Chamán Mejora PvE', NULL),
(13436, 'Druid Caster PvP', NULL, NULL, NULL, NULL, NULL, 'Druida Caster PvP', 'Druida Caster PvP', NULL),
(13437, 'Druid Heal PvP', NULL, NULL, NULL, NULL, NULL, 'Druida Heal PvP', 'Druida Heal PvP', NULL),
(13438, 'Druid Feral PvP', NULL, NULL, NULL, NULL, NULL, 'Druida Feral PvP', 'Druid Feral PvP', NULL),
(13439, 'Druid Caster PvE', NULL, NULL, NULL, NULL, NULL, 'Druida Caster PvE', 'Druida Caster PvE', NULL),
(13440, 'Druid Heal PvE', NULL, NULL, NULL, NULL, NULL, 'Druida Heal PvE', 'Druida Heal PvE', NULL),
(13441, 'Druid Feral PvE', NULL, NULL, NULL, NULL, NULL, 'Druida Feral PvE', 'Druid Feral PvE', NULL),
(13442, 'Teleport to Stormwind', NULL, NULL, NULL, NULL, NULL, 'Teletransporte a Ventormenta', 'Teletransporte a Ventormenta', NULL),
(13443, 'Teleport to Orgrimmar', NULL, NULL, NULL, NULL, NULL, 'Teletransporte a Orgrimmar', 'Teletransporte a Orgrimmar', NULL);